### ISSUE TITLE
Session.lvclass:Process Packet.vi resulting in a Fixed Header of 0 causing a process violation

### ISSUE THREAD

**Issue by carlosjfmrocha** [LabVIEW-Open-Source/MQTT-Connection#8] opened 2023-04-17 20:38 UTC
In our application, we have multiple MQTT clients running (a requirement due to the independent/parallel nature of the different components of the application) and subscribing/publishing to a broker that is also connected to some other MQTT clients developed in other languages/platforms. These other clients are PLCs that are publishing multiple topics at a relative fast cadence (10ms or lower).

What is happening is that after sometime the broker is closing the connection to some of our LabVIEW clients. I have checked the log of the HiveMQ broker and found that the broker is clearing the TCP connection with the reason: "Sent a message with message type '0'.".

I am able to recreate this is behaviour very easily buy setting up a Publisher and Subscriber using the DropVIs available in MQTT Client pallete and setting up the timeout of the event structure of the Publisher to 0. In this scenario, the publisher as no issues but the subscriber quickly loses connection with the error I mentioned above.
 
I tried looking around and noticed that, in fact, if I place a breakpoint whenever "ControlPacketresponse" in the "MQTT Base.lvlib:Session.lvclass:Process Packet.vi" has a fixed header of 0 right before Enqueueing to the Session Mailbox I am able to catch it.

However, despite a few hours trying to figure it out, I still haven't found how it's possible for the control packet to show up with the fixed header as 0. I believe the issue is some sort of concurrency that shows up when I overload it with multiple fast-paced clients or by just setting one publisher with 0 timeout publishes.

**Comment by francois-normandin** [comment] 2023-04-18 14:23
@carlosjfmrocha Thanks for the report.
I am unable to reproduce the problem with the LV MQTT Broker. I can publish with 0ms timeout and all the points are received by the subscribe. In my test, they remained perfectly in sync after >15M points transferred at a rate of approx 10k points/s

Question: Are you using QoS = 0 for this test? The reason I'm asking is that for a subscriber in QoS = 0, there are no outgoing responses to the server, so the invalid packet type 0 must originate from HiveMQ itself (not from a SUBACK packet). That HiveMQ closes the connection is the proper response to a protocol violation. In fact, the subscriber should also close the connection if it receives an invalid message from the broker.
Could it be that you are reaching the capacity of the broker? I'm no expert, but if a queue builds up in whatever buffer the server uses to process and route subscriptions, there might be a tipping point where there is an overflow?

If you are using QoS = 1, then the issue might be in the production of the SUBACK packet.

If you want to further look into the incoming stream from the subscriber's perspective, you could add a logger in the incoming byte stream to record all the bytes. You could then replay them with the packet parsing node to see if everything seems fine on the incoming stream from the server, (Unfortunately, there is an injection mechanism only for the broker... not the clients)

![image](https://user-images.githubusercontent.com/11728548/232807475-73420858-e4e3-460f-bd1f-b902c4e88feb.png)

**Comment by carlosjfmrocha** [comment] 2023-04-22 09:37
Hello @francois-normandin 
Thank you very much for looking into it.
I did some more trials to try to identify where the issue might be:

- I swapped between 2 brokers (HiveMQ and Mosquitto)
- I tried maintaining the same publisher (The DropVI_SimpleClientPublisher from the MQTT Client Pallete) and change the subscriber to a python paho based one. No issues, so the publisher is fine.
- I tried changing the publisher to a python paho based one and maintaining the same subscriber (DropVI_SimpleClientSubscriber from the MQTT Client Pallete + a Ping loop for the KeepAlive) and the issue continued.
- I implemented the functionality to toggle the Ping ON and OFF. I started as OFF with the python subscriber and there was no issue. I toggled the Ping ON and a bit later I got the Message Type 0 being sent. 

I will investigate a bit further and come back with more information.

**Comment by carlosjfmrocha** [comment] 2023-04-22 11:30
Hello again @francois-normandin 

I found the cause of the issue but I would require your expertise to better understand the best way to go around and solve it.
Basically what's happening is that in the scenario I had setup with my subscriber I am receiving a bunch of PUBLISH Control Packets with QoS 0 and from time to time I am sending a PINGREQ Control Packet.
The Control Packet creates a Pending ACK with Packet Identifier 0.
If before handling that ACK a PUBLISH Control Packet with QoS 0 arrives with Packed Identifier 0, the subscriber will wrongly respond with a default Control Packet with Fixed Header 0, causing the Protocol Violation, as it believes the ACK is for the PUBLISH Control Packet it just received, despite it being with QoS 0.
This is handled in the "MQTT Base.lvlib:Session.lvclass:SeachACKs(byID)" in "MQTT Base.lvlib:Session.lvclass:Process Packet.vi".

![image](https://user-images.githubusercontent.com/102086744/233781434-e6e68bbf-5eac-4a40-8382-1cba766504bf.png)

![image](https://user-images.githubusercontent.com/102086744/233781512-c572731b-3ec5-46bd-8d94-54f51df6f43d.png)

To confirm this suspicion, I changed the "MQTT_Control_Packets.lvlib:ControlPacket.lvclass:Handle Packet Identifier.vi" to use a 999 packet identifier if the previous VI (hasPreviousIdentifier) concludes that there is no Packet Identifier, instead of the default 0.

![image](https://user-images.githubusercontent.com/102086744/233781369-0e5b9ee9-5e17-4c51-beec-b4d044101ef4.png)

After this change, the issue disappeared.
I am not sure if this might be resulting from the broker mishandling the Packet Identifiers or some mistake on the client side. Either way, do you think it makes sense to use a non-expected value for the Packet Identifier instead of 0, which is a valid one, in the scenarios where no Packet Identifier arrives?

My understanding might be flawed, so if I did not made myself clear, please do let me know so I can try to better explain it.
Thank you.

**Comment by francois-normandin** [comment] 2023-04-22 14:16
@carlosjfmrocha Thanks for the additional details.

I think what you describe is similar to a prior QoS related issue we've fixed. I will trace it back and compare how it was resolved to your proposal. I think your proposal is in line with the fix we had found in another circumstance.

**Comment by carlosjfmrocha** [comment] 2023-04-27 19:58
Hello @francois-normandin 
Were you able to trace it back and check your fix at the time?
Thank you.

**Comment by francois-normandin** [comment] 2023-05-08 00:56
@carlosjfmrocha I have not been able to quickly find the similar issue I was referring to. Supposedly I didn't label it as "bug". I did have a quick glance through the list of resolved issues and could not stumble on it either.
Admittedly, I've not been able to find time to implement the fix either.

**Comment by francois-normandin** [comment] 2024-01-01 17:27
@carlosjfmrocha No fix has been published yet for this issue. 
I just had a minute or two to look at this again, and I'm looking at a corrective action.

I think it might be simpler than adding a fixed ID. I'll simply expose the "Has Packet Identifier" on the Read packet Identifier and use it in the Process packet to skip...

![image](https://github.com/LabVIEW-Open-Source/MQTT-Connection/assets/11728548/5ebc610b-7e25-4ac9-8a58-47c5ba64d0dc)

The packets that have Identifiers will resolve to the true case (unchanged) while the others will move to the other case, where only PINGREQ should prepare a response. This scheme will make it compatible with future versions that might introduce more of these types of no-identifier packets (doubtful, but we never know). 

![image](https://github.com/LabVIEW-Open-Source/MQTT-Connection/assets/11728548/36335379-6323-4707-a055-5fdbeecb4560)

**Comment by francois-normandin** [comment] 2024-01-01 17:52
Note to self. Check this location too.
![image](https://github.com/LabVIEW-Open-Source/MQTT-Connection/assets/11728548/38480232-d62e-4a8d-a753-a41c196233bd)

And in the process.
![image](https://github.com/LabVIEW-Open-Source/MQTT-Connection/assets/11728548/2e81b7f4-af7a-4532-afb8-0749a04be800)

**Comment by francois-normandin** [comment] 2024-01-01 19:44
And this "Send Packet" client method:
![image](https://github.com/LabVIEW-Open-Source/MQTT-Connection/assets/11728548/d2f98aa6-0eb7-4d31-8b8a-ea0a89507c69)

![Uploading image.png…]()

**Comment by francois-normandin** [comment] 2024-01-04 16:21
@carlosjfmrocha 
I will have a fix over the weekend. Slightly different than depicted above. Documentation will be here on release.

**Comment by francois-normandin** [comment] 2024-01-06 19:52
Solution implemented: 

- Modified the stored ID from U16 to U32.
- All Acks use the lower 16 bits (0x0000 0001 to 0x 0000 FFFF), but PINGREQ and PINGRESP will be constructed as 1 << 17 (0x0001 0000). Ping responses
- Fixed the reservation of 0x0000 ID, which are not allowed
- Fixed the ID generator to skip 0x0000
- Modified the ack map to a variant attribute (faster than 1D array search)

**Comment by francois-normandin** [comment] 2024-01-14 20:20
Fixed in Release 4.1.2.

**Closed as completed by francois-normandin** 2024-01-14 20:20 UTC
